Initializing project
desapp-2022c1-grupo2/desapp-backend pull request #1
Opened 2022-05-01 16:11 UTC by tomastoloza

things added:

typescript
typeorm
postgres
gitignore

using https://typeorm.io/#installation and https://typeorm.io/#quick-start

2022-05-01 16:13 UTC, tomastoloza commented
![](https://github.trello.services/images/mini-trello-icon.png) [Crear el repositorio para el backend](https://trello.com/c/87wghK8f/24-crear-el-repositorio-para-el-backend)

2022-05-03 21:39 UTC, tomastoloza commented
added dotenv library to manage credentials

2022-05-18 21:36 UTC, adrianyaniri approved these changes

2022-05-18 21:36 UTC, adrianyaniri commented on README.md
> +
????

2022-05-18 21:37 UTC, adrianyaniri requested changes

2022-05-18 21:37 UTC, adrianyaniri commented on README.md
> +
??

2022-05-18 21:39 UTC, merged