Feature/tp
desapp-2022c1-grupo2/desapp-backend pull request #20
Opened 2022-07-18 19:37 UTC by adrianyaniri

Se implemento solo los getAll y getById de los TP. Como solo necesitamos eso, por eso no use los Basic

2022-07-18 20:57 UTC, tomastoloza requested changes
Hay cambios en los packages, que se agregó/quitó? Y otros comentarios.. te doy una mano o lo ves vos?

2022-07-18 20:57 UTC, tomastoloza commented on src/modules/tp/entities/tp.entity.ts
> +@Entity('trabajo')
```suggestion
@Entity('assignment')
```

2022-07-18 20:57 UTC, tomastoloza commented on src/modules/tp/entities/tp.entity.ts
> +export class TpEntiy extends BaseEntity {
Renombrar entidad y archivo, veo que se borraron
```suggestion
export class Assignment extends BaseEntity {
```

2022-07-18 20:57 UTC, tomastoloza commented on src/modules/tp/entities/tp.entity.ts
> +    @Column( { name: 'description'})
Cambiar el name para que matchee con la db asi no se crean campos en la tabla
```suggestion
    @Column( { name: 'descripcion'})
```

2022-07-18 20:57 UTC, tomastoloza commented on src/modules/tp/entities/tp.entity.ts
> +}
También habria que agregar los createdAt, y updatedAt como en baseEntity

2022-07-19 01:02 UTC, adrianyaniri commented on src/modules/tp/entities/tp.entity.ts
> +}
El tema esta que en la bd original no estan esos campos

2022-07-19 01:44 UTC, closed without merging