Estadisticas
desapp-2022c1-grupo2/desapp-backend pull request #32
Opened 2022-10-05 14:43 UTC by adrianyaniri

Este PR no esta terminado. Se creo solo para que puedan ver algunas estadisticas no todas

2022-10-07 21:00 UTC, adrianyaniri commented
@tomastoloza Actualize el branch con las nuevas estadisticas

2022-10-11 22:53 UTC, tomastoloza requested changes

2022-10-11 22:53 UTC, tomastoloza commented on src/modules/admin/entities/admin.entity.ts
> +  @Column({ unique: false })
porqué cambió a false?

2022-10-11 22:53 UTC, tomastoloza commented on src/modules/assignment/assignment.controller.ts
> +  async AllAssignmentForJtp(@Param('jtpId') id: number): Promise<Assignment[]> {
```suggestion
  async getAllAssignmentForJtp(@Param('jtpId') id: number): Promise<Assignment[]> {
```

2022-10-11 22:53 UTC, tomastoloza commented on src/modules/assignment/assignment.service.ts
> +  async countAllAssignments(): Promise<number> {
No está en baseService?

2022-10-11 22:53 UTC, tomastoloza commented on src/modules/student/student.controller.ts
> +  @Get('count')
No está en baseController?

2022-10-11 22:53 UTC, tomastoloza commented on src/modules/student/student.service.ts
> +  async countAll(): Promise<number> {
No está en baseService?

2022-10-11 22:58 UTC, tomastoloza commented on src/modules/assignment/assignment.controller.ts
> +  async AllAssignmentForJtp(@Param('jtpId') id: number): Promise<Assignment[]> {
este statistics/:jtpId no deberia estar en un modulo statistics o stats aparte?

2022-10-16 19:07 UTC, closed without merging