Deploy && Validaciones de password
desapp-2022c1-grupo2/desapp-backend pull request #39
Opened 2022-10-25 13:35 UTC by adrianyaniri

2022-10-26 20:46 UTC, tomastoloza requested changes

2022-10-26 20:46 UTC, tomastoloza commented on src/config/database.config.ts
> +    database: process.env.DATABASE_NAME_HEROKU,
Esto va a romper las apps que ya existen, no se puede mantener el nombre?

2022-10-26 20:46 UTC, tomastoloza commented on src/modules/admin/dto/created-admin.dto.ts
> +      message: "Password too weak",
Que más valida esto ademas de la longitud?
Luego en el front tendriamos que mostrar los requerimientos si falla la creación
Sea por ejemplo minimo de 8 caracteres, etc

2022-10-27 12:30 UTC, adrianyaniri commented on src/config/database.config.ts
> +    database: process.env.DATABASE_NAME_HEROKU,
Si se puede volver al nombre anterior

2022-10-27 12:31 UTC, adrianyaniri commented on src/modules/admin/dto/created-admin.dto.ts
> +      message: "Password too weak",
Ademas de la longuitud, los Matches son los ditintos caracteres que podes usar.
Se pueden sacar los que creas que no vamos a usar

2022-11-03 20:46 UTC, closed without merging