Feature/docker
desapp-2022c1-grupo2/desapp-backend pull request #7
Opened 2022-06-20 20:39 UTC by adrianyaniri

2022-06-20 22:20 UTC, tomastoloza requested changes
Excelente laburo, dejé un par de comments

2022-06-20 22:20 UTC, tomastoloza commented on .env.example
> +DATBASE_HOST=
```suggestion
DATABASE_HOST=
```

2022-06-20 22:20 UTC, tomastoloza commented on .env.example
> +DATABASE_DATABAS=
```suggestion
DATABASE_DATABASE=
```

2022-06-20 22:20 UTC, tomastoloza commented on README.md
> +- DATABASE_PORT
Lo mismo que arriba

2022-06-20 22:20 UTC, tomastoloza commented on docker-compose.yml
> +version: '3.7'
No deberíamos usar un mariadb? Yo creo que no hay problema para que sea de desarrollo igual.

2022-06-20 22:20 UTC, tomastoloza commented on src/config/const.ts
> +export const SERVER_PORT = 'PORT';
Me confundia a que hacia referencia el 'PORT', por ahi conviene llamarlo NEST_PORT o similar

2022-06-20 22:20 UTC, tomastoloza commented on src/app.module.ts
> +         envFilePath: `.env.${ process.env.NODE_ENV || 'production'}`, // default apunta a .env.development
Esta linea no me funciona, despues la revisamos, pero en definitiva seteando en el `.env` la var NODE_ENV=development no me toma el archivo

2022-06-21 00:04 UTC, adrianyaniri commented on src/config/const.ts
> +export const SERVER_PORT = 'PORT';
PORT llama al puerto donde corre el servidor

2022-06-21 01:38 UTC, merged